apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: geo-distance-pipeline
  generateName: geo-distance-pipeline-run-
  namespace: geo-distance-api
  annotations:
    backstage.io/kubernetes-id: backstage-demo-app  
  finalizers:
  - chains.tekton.dev/pipelinerun
spec:
  params:
  - name: image-name
    value: geo-distance
  - name: image-tag
    value: "0.1"
  pipelineRef:
    name: geo-distance-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: ocs-storagecluster-ceph-rbd
        volumeMode: Filesystem
      status: {}
