apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: geo-distance-pipeline
  namespace: geo-distance-api
  annotations:
    backstage.io/kubernetes-id: backstage-demo-app
spec:
  params:
  - default: geo-distance
    name: image-name
    type: string
  - default: "0.1"
    name: image-tag
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: https://github.com/stefan-bergstein/geo-distance-api
    - name: revision
      value: ""
    - name: refspec
      value: ""
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: subdirectory
      value: ""
    - name: sparseCheckoutDirectories
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: ""
    - name: httpsProxy
      value: ""
    - name: noProxy
      value: ""
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
    - name: userHome
      value: /home/git
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: create-imagestream
    params:
    - name: SCRIPT
      value: oc create imagestream $(params.image-name) --lookup-local=true --dry-run=client
        -o yaml | oc apply -f -
    - name: VERSION
      value: latest
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: openshift-client
  - name: build-image
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.image-name):$(params.image-tag)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:00795fafdab9bbaa22cd29d1faa1a01e604e4884a2c935c1bf8e3d1f0ad1c084
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Containerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: PUSH_EXTRA_ARGS
      value: ""
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - create-imagestream
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  workspaces:
  - name: workspace
